# Manifest źródeł SpeakLeash (source→SPDX) — SZKIELET. Ref: maggi-vct.
# TODO: uzupełnić realne licencje (Bartek Kobyliński). UNKNOWN→WARN (nie blokuje); NC/ND→FAIL.
# Wpięcie: przyszła karta datasetu SpeakLeash ustawi `source_manifest: sources.yaml`.
sources:
  plwiki: {license: UNKNOWN}
  1000_novels_corpus_CLARIN-PL: {license: UNKNOWN}
  wolne_lektury_corpus: {license: UNKNOWN}
  CEON_corpus: {license: UNKNOWN}
  thesis: {license: UNKNOWN}
  forum_forum_programosy_pl_corpus: {license: UNKNOWN}
  web_synt_0002: {license: UNKNOWN}
  web_synt_0005: {license: UNKNOWN}
  web_synt_0006: {license: UNKNOWN}
  web_synt_0007: {license: UNKNOWN}
  web_synt_0008: {license: UNKNOWN}
  web_synt_0009: {license: UNKNOWN}
  web_synt_0010: {license: UNKNOWN}
  web_synt_0011: {license: UNKNOWN}
  web_synt_0012: {license: UNKNOWN}
  web_synt_0013: {license: UNKNOWN}
  web_synt_0014: {license: UNKNOWN}
  web_synt_0015: {license: UNKNOWN}
  web_synt_0017: {license: UNKNOWN}
  HPLT_100: {license: UNKNOWN}
  HPLT_102: {license: UNKNOWN}
  HPLT_103: {license: UNKNOWN}
  HPLT_104: {license: UNKNOWN}
  HPLT_105: {license: UNKNOWN}
  HPLT_106: {license: UNKNOWN}
  HPLT_109: {license: UNKNOWN}
  HPLT_111: {license: UNKNOWN}
  HPLT_112: {license: UNKNOWN}
  HPLT_117: {license: UNKNOWN}
  HPLT_118: {license: UNKNOWN}
  HPLT_119: {license: UNKNOWN}
  HPLT_120: {license: UNKNOWN}
  HPLT_121: {license: UNKNOWN}
  HPLT_123: {license: UNKNOWN}
  HPLT_125: {license: UNKNOWN}
  HPLT_138: {license: UNKNOWN}
  HPLT_139: {license: UNKNOWN}
  HPLT_15: {license: UNKNOWN}
  HPLT_16: {license: UNKNOWN}
  HPLT_18: {license: UNKNOWN}
  HPLT_190: {license: UNKNOWN}
  HPLT_191: {license: UNKNOWN}
  HPLT_194: {license: UNKNOWN}
  HPLT_195: {license: UNKNOWN}
  HPLT_196: {license: UNKNOWN}
  HPLT_197: {license: UNKNOWN}
  HPLT_198: {license: UNKNOWN}
  HPLT_199: {license: UNKNOWN}
  HPLT_200: {license: UNKNOWN}
  HPLT_201: {license: UNKNOWN}
  HPLT_202: {license: UNKNOWN}
  HPLT_203: {license: UNKNOWN}
  HPLT_210: {license: UNKNOWN}
  HPLT_213: {license: UNKNOWN}
  HPLT_214: {license: UNKNOWN}
  HPLT_215: {license: UNKNOWN}
  HPLT_217: {license: UNKNOWN}
  HPLT_218: {license: UNKNOWN}
  HPLT_219: {license: UNKNOWN}
  HPLT_220: {license: UNKNOWN}
  HPLT_264: {license: UNKNOWN}
  HPLT_27: {license: UNKNOWN}
  HPLT_275: {license: UNKNOWN}
  HPLT_276: {license: UNKNOWN}
  HPLT_45: {license: UNKNOWN}
  HPLT_47: {license: UNKNOWN}
  HPLT_48: {license: UNKNOWN}
  HPLT_49: {license: UNKNOWN}
  HPLT_50: {license: UNKNOWN}
  HPLT_51: {license: UNKNOWN}
  HPLT_52: {license: UNKNOWN}
  HPLT_54: {license: UNKNOWN}
  HPLT_59: {license: UNKNOWN}
  HPLT_60: {license: UNKNOWN}
  HPLT_62: {license: UNKNOWN}
  HPLT_63: {license: UNKNOWN}
